import Head from 'next/head'
import Header from '../Components/Header'
import ListsCommits from '../Components/ListsCommits'
import Pagination from '../Components/Pagination'
import React, {useState} from 'react'

export default function Home({results}) {

  const [posts] = useState(results);
  const [loading] = useState(false);
  const [currenPage, setCurrenPage] = useState(1)
  const [postsPerPage] = useState(5);

  const indexOfLastPost = currenPage * postsPerPage;
  const indexOfFirstPost = indexOfLastPost - postsPerPage;
  const currentPosts = posts.slice(indexOfFirstPost, indexOfLastPost)

  const paginate = (pageNumber) => setCurrenPage(pageNumber)

  return (
    <div >
      <Head>
        <title>Commits</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <ListsCommits results={currentPosts} loading={loading}/>
        <Pagination postsPerPage={postsPerPage} totalPost={posts.length} paginate={paginate} />
    </div>
  )
}


export async function getServerSideProps(context) {
  const USERNAME = process.env.USERNAME;
  const REPO = process.env.REPO;
  const SHA = process.env.SHA;
  const url = `https://api.github.com/repos/dannyaguirre09/TestFulltimeForce/commits`;
  const result = await fetch(url).then(res => res.json()).catch(err => err.json());
  return {props: {results: result}}
}