import Head from 'next/head'
import Header from '../Components/Header'
import ListsCommits from '../Components/ListsCommits'

export default function Home({results}) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header />
        <ListsCommits results={results}/>
    </div>
  )
}


export async function getServerSideProps(context) {
  const USERNAME = process.env.USERNAME;
  const REPO = process.env.REPO;
  const SHA = process.env.SHA;
  const url = `https://api.github.com/repos/dannyaguirre09/TestFulltimeForce/commits?sha=d5b9225a4404df1057c6702456141479ddbf1fe0`;
  const result = await fetch(url).then(res => res.json()).catch(err => err.json());
  return {props: {results: result}}
}